%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.5

-ifndef(login_pb).
-define(login_pb, true).

-define(login_pb_gpb_version, "4.10.5").

-ifndef('C2S_HEARTBEAT_PB_H').
-define('C2S_HEARTBEAT_PB_H', true).
-record(c2s_heartbeat,
        {
        }).
-endif.

-ifndef('S2C_HEARTBEAT_PB_H').
-define('S2C_HEARTBEAT_PB_H', true).
-record(s2c_heartbeat,
        {timestamp = 0          :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('C2S_LOGIN_PB_H').
-define('C2S_LOGIN_PB_H', true).
-record(c2s_login,
        {account = <<>>         :: iodata() | undefined, % = 1
         passwd = <<>>          :: iodata() | undefined, % = 2
         machine_id = <<>>      :: iodata() | undefined, % = 3
         terminal = 0           :: integer() | undefined, % = 4, 32 bits
         model = <<>>           :: iodata() | undefined, % = 5
         channel = <<>>         :: iodata() | undefined % = 6
        }).
-endif.

-ifndef('S2C_LOGIN_PB_H').
-define('S2C_LOGIN_PB_H', true).
-record(s2c_login,
        {code = 0               :: integer() | undefined, % = 1, 32 bits
         user_id = 0            :: integer() | undefined % = 2, 32 bits
        }).
-endif.

-endif.
