%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.5

-ifndef(player_pb).
-define(player_pb, true).

-define(player_pb_gpb_version, "4.10.5").

-ifndef('C2S_PLAYER_INFO_PB_H').
-define('C2S_PLAYER_INFO_PB_H', true).
-record(c2s_player_info,
        {
        }).
-endif.

-ifndef('S2C_PLAYER_INFO_PB_H').
-define('S2C_PLAYER_INFO_PB_H', true).
-record(s2c_player_info,
        {name = <<>>            :: iodata() | undefined, % = 1
         coin = 0               :: integer() | undefined, % = 2, 32 bits
         store_coin = 0         :: integer() | undefined, % = 3, 32 bits
         face_id = 0            :: integer() | undefined, % = 4, 32 bits
         gender = 0             :: integer() | undefined % = 5, 32 bits
        }).
-endif.

-endif.
