%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.5

-ifndef(test_pb).
-define(test_pb, true).

-define(test_pb_gpb_version, "4.10.5").

-ifndef('C2S_TEST_PB_H').
-define('C2S_TEST_PB_H', true).
-record(c2s_test,
        {int_v = 0              :: integer() | undefined, % = 1, 32 bits
         string_v = <<>>        :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('VALUE_PB_H').
-define('VALUE_PB_H', true).
-record(value,
        {int_v = 0              :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('S2C_TEST_PB_H').
-define('S2C_TEST_PB_H', true).
-record(s2c_test,
        {int_v = 0              :: integer() | undefined, % = 1, 32 bits
         string_v = <<>>        :: iodata() | undefined % = 2
        }).
-endif.

-endif.
